var path = `Redirected from /catalog/?q=kxd+w55 to /mobile-phones/?q=kxd+w55
Redirected from /catalog/?q=kxd+w50 to /mobile-phones/?q=kxd+w50
Redirected from /catalog/?q=itel to /smartphones/itel/
Redirected from /catalog/?q=spark+2 to 	/phones-tablets/tecno/?q=spark+2
Redirected from /smartphones/?q=x606 to /smartphones/infinix/?q=x606
Redirected from /catalog/?q=nokia to /phones-tablets/nokia/?q=nokia
Redirected from /smartphones/?q=iphone+6s to /smartphones/apple/?q=iphone+6s
Redirected from /smartphones/?q=camon+11 to /smartphones/tecno/?q=camon+11
Redirected from /catalog/?q=hot+6+pro to /phones-tablets/infinix/?q=hot+6+pro
Redirected from /smartphones/?q=infinix+note to /smartphones/infinix/?q=infinix+note
Redirected from /catalog/?q=pouvoir+2 to /phones-tablets/tecno/?q=pouvoir+2
Redirected from /catalog/?q=rechargeable+fans to /home-office/?q=rechargeable+fans
Redirected from /smartphones/?q=spark to /smartphones/tecno/?q=spark
Redirected from /catalog/?q=huawei+y9 to /phones-tablets/huawei/?q=huawei+y9
Redirected from /catalog/?q=refrigerator to /appliances-fridges-freezers/
Redirected from /smartphones/?q=htc to /smartphones/htc/
Redirected from /catalog/?q=iphone+8 to /phones-tablets/apple/?q=iphone+8
Redirected from /catalog/?q=galaxy+s8 to /phones-tablets/samsung/?q=galaxy+s8
Redirected from /catalog/?q=galaxy+s7 to /phones-tablets/samsung/?q=galaxy+s7
Redirected from /catalog/?q=infinix+hot+6x to /phones-tablets/infinix/?q=infinix+hot+6x
Redirected from /catalog/?q=leagoo to /phones-tablets/leagoo/
Redirected from /catalog/?q=human+hair to /human-hair-pieces/
Redirected from /catalog/?q=Bluetooth+speaker to /electronics/?q=bluetooth+speaker
Redirected from /catalog/?q=iphone+xs+max to /phones-tablets/apple/?q=iphone+xs+max
Redirected from /catalog/?q=Jeans to /womens-jeans/
Redirected from /catalog/?q=hot+s3 to /phones-tablets/infinix/?q=hot+s3
Redirected from /catalog/?q=galaxy+s9 to /phones-tablets/samsung/?q=galaxy+s9
Redirected from /catalog/?q=j4 to /phones-tablets/samsung/?q=j4
Redirected from /catalog/?q=umidigi to /phones-tablets/umidigi/
Redirected from /catalog/?q=oukitel to /phones-tablets/oukitel/
Redirected from /catalog/?q=balenciaga to /category-fashion-by-jumia/balenciaga/
Redirected from /catalog/?q=mobile+wardrobe to /home-office/?q=mobile+wardrobe
Redirected from /catalog/?q=sewing+machine to /home-office/?q=sewing+machine
Redirected from /catalog/?q=slippers to /category-fashion-by-jumia/fashion-brand/?q=slippers
Redirected from /catalog/?q=drone to /toys-games/?q=drone
Redirected from /smartphones/?q=iphone to /smartphones/apple/?q=iphone
Redirected from /catalog/?q=tv+stand to /home-office/?q=tv+stand
Redirected from /catalog/?q=Bed to /home-office/?q=bed
Redirected from /catalog/?q=camon11 to /phones-tablets/tecno/?q=camon11
Redirected from /catalog/?q=headset to /phones-tablets/?q=headset
Redirected from /smartphones/?q=hot+5 to /smartphones/infinix/?q=hot+5
Redirected from /catalog/?q=waist+trainer to /sporting-goods/?q=waist+trainer
Redirected from /catalog/?q=wristwatch to /category-fashion-by-jumia/?q=wristwatch
Redirected from /catalog/?q=ps3 to /video-games/?q=ps3
Redirected from /catalog/?q=watches to /womens-watches/
Redirected from /catalog/?q=women+shoes to /womens-shoes/
Redirected from /catalog/?q=cooker to /home-office/?q=cooker
Redirected from /catalog/?q=hisense to /electronics/hisense/
Redirected from /catalog/?q=wigs to /extensions-wigs-accessories/
Redirected from /catalog/?q=men+sneakers to /men-sneakers/
Redirected from /catalog/?q=j6+plus to /phones-tablets/samsung/?q=j6+plus
Redirected from /catalog/?q=cubot to /phones-tablets/cubot/
Redirected from /catalog/?q=wx3 to /phones-tablets/tecno/?q=wx3
Redirected from /catalog/?q=stabilizer to /electronics/?q=stabilizer
Redirected from /catalog/?q=apetamin to /health-beauty/?q=apetamin
Redirected from /catalog/?q=psp to /video-games/?q=psp
Redirected from /catalog/?q=fifa+19 to /video-games/?q=fifa+19
Redirected from /catalog/?q=wig to /extensions-wigs-accessories/
Redirected from /catalog/?q=pouvoir to /phones-tablets/tecno/?q=pouvoir
Redirected from /catalog/?q=j8 to /phones-tablets/?q=j8
Redirected from /catalog/?q=letv to /phones-tablets/letv/
Redirected from /catalog/?q=iphone+7+plus to /phones-tablets/apple/?q=iphone+7+plus
Redirected from /catalog/?q=headphones to /electronics/?q=headphones
Redirected from /catalog/?q=shirt to /category-fashion-by-jumia/?q=shirt
Redirected from /catalog/?q=camon+x to /phones-tablets/tecno/?q=camon+x
Redirected from /catalog/?q=iphone+x+max to /phones-tablets/apple/?q=iphone+x+max
Redirected from /catalog/?q=bontel to /phones-tablets/bontel/?q=bontel
Redirected from /catalog/?q=iphones to /phones-tablets/apple/?q=iphones
Redirected from /catalog/?q=sneaker to /men-sneakers/
Redirected from /catalog/?q=ceiling+fan to /home-office/?q=ceiling+fan
Redirected from /catalog/?q=durag to /category-fashion-by-jumia/?q=durag
Redirected from /catalog/?q=weavon to /health-beauty/?q=weavon
Redirected from /catalog/?q=wardrobe to /home-office/?q=wardrobe
Redirected from /catalog/?q=speaker to /electronics/?q=speaker
Redirected from /catalog/?q=wrist+watches to /watches/
Redirected from /catalog/?q=bluetooth+headset to /electronics/?q=bluetooth+headset
Redirected from /catalog/?q=gas+cylinder to /home-office/?q=gas+cylinder
Redirected from /catalog/?q=oven to /home-office/?q=oven
Redirected from /catalog/?q=dstv to /electronics/dstv/
Redirected from /catalog/?q=smart+2+pro to /phones-tablets/infinix/?q=smart+2+pro
Redirected from /catalog/?q=jacket to /category-fashion-by-jumia/?q=jacket
Redirected from /catalog/?q=printer to /computing/?q=printer
Redirected from /catalog/?q=camon+cx to /phones-tablets/tecno/?q=camon+cx
Redirected from /catalog/?q=huawei+y9+2019 to /phones-tablets/huawei/?q=huawei+y9+2019
Redirected from /catalog/?q=hot+6x to /phones-tablets/infinix/?q=hot+6x
Redirected from /catalog/?q=k7 to /phones-tablets/?q=k7
Redirected from /catalog/?q=blackberry to /phones-tablets/blackberry/?q=blackberry
Redirected from /catalog/?q=cars to /automobile/?q=cars
Redirected from /catalog/?q=binatone+blender to /home-office/binatone/?q=binatone+blender
Redirected from /catalog/?q=earpiece to /electronics/?q=earpiece
Redirected from /catalog/?q=wallpaper to /home-office/?q=wallpaper
Redirected from /catalog/?q=sandal to /category-fashion-by-jumia/?q=sandal
Redirected from /catalog/?q=iphone+5s to /phones-tablets/apple/?q=iphone+5s
Redirected from /catalog/?q=cake+mixer to /home-office/?q=cake+mixer
Redirected from /catalog/?q=loafers to /category-fashion-by-jumia/?q=loafers
Redirected from /catalog/?q=iphone+xr to /phones-tablets/apple/?q=iphone+xr
Redirected from /catalog/?q=dress to /category-fashion-by-jumia/?q=dress
Redirected from /catalog/?q=galaxy+j6 to /phones-tablets/samsung/?q=galaxy+j6	
Redirected from /catalog/?q=necklace to /category-fashion-by-jumia/?q=necklace
Redirected from /catalog/?q=solar+panel to /electronics/?q=solar+panel
Redirected from /catalog/?q=women+sneakers to /womens-sneakers/
Redirected from /catalog/?q=ring to /category-fashion-by-jumia/?q=ring
Redirected from /catalog/?q=itel+s13 to /phones-tablets/itel/?q=itel+s13
Redirected from /catalog/?q=canvas to /category-fashion-by-jumia/?q=canvas
Redirected from /catalog/?q=f3 to /phones-tablets/tecno/?q=f3
Redirected from /catalog/?q=iphone+6s+plus to /phones-tablets/apple/?q=iphone+6s+plus
Redirected from /catalog/?q=iphone6 to /phones-tablets/apple/?q=iphone6
Redirected from /catalog/?q=belt to /category-fashion-by-jumia/?q=belt
Redirected from /catalog/?q=ladies+sneakers to /womens-sneakers/
Redirected from /catalog/?q=suit to /category-fashion-by-jumia/?q=suit
Redirected from /catalog/?q=electric+kettle to /home-office/?q=electric+kettle
Redirected from /catalog/?q=jumpsuit to /womens-clothing/?q=jump+suit
Redirected from /catalog/?q=shirts to /category-fashion-by-jumia/?q=shirts
Redirected from /catalog/?q=y9 to /phones-tablets/huawei/?q=y9
Redirected from /catalog/?q=dresses to /womens-dresses/
Redirected from /catalog/?q=iphone+4 to /phones-tablets/apple/?q=iphone+4
Redirected from /catalog/?q=wall+paper to /home-office/?q=wall+paper
Redirected from /catalog/?q=ps4+console to /video-games/?q=ps4+console
Redirected from /catalog/?q=chest+freezer to /home-office/?q=chest+freezer
Redirected from /catalog/?q=tops to /womens-tops-tees/
Redirected from /catalog/?q=sunglasses to /watches-sunglasses/
Redirected from /catalog/?q=bicycle to /sporting-goods/?q=bicycle
Redirected from /catalog/?q=casio to /watches-sunglasses/?q=casio
Redirected from /catalog/?q=gotv to /electronics/gotv/
Redirected from /catalog/?q=itel+s33 to /smartphones/itel/?q=itel+s33
Redirected from /catalog/?q=piano to /musical-instruments/?q=piano
Redirected from /smartphones/?q=iphone+6 to /smartphones/apple/?q=iphone+6
Redirected from /catalog/?q=iphone+6+plus to /phones-tablets/apple/?q=iphone+6+plus
Redirected from /catalog/?q=beard+oil to /health-beauty/beard-oil/
Redirected from /catalog/?q=headphone to /electronics/?q=headphone
Redirected from /catalog/?q=hoodie to /category-fashion-by-jumia/?q=hoodie
Redirected from /catalog/?q=smart+watches to /phones-tablets/smartwatch/
Redirected from /catalog/?q=wireless+earpiece to /electronics/?q=wireless+earpiece
Redirected from /catalog/?q=blenders to /home-office/?q=blenders
Redirected from /catalog/?q=jean to /category-fashion-by-jumia/?q=jean
Redirected from /catalog/?q=t+shirt to /category-fashion-by-jumia/?q=t+shirt
Redirected from /catalog/?q=freezers to /appliances-fridges-freezers/
Redirected from /catalog/?q=bracelet to /category-fashion-by-jumia/?q=bracelet
Redirected from /catalog/?q=dell to /computing/dell/
Redirected from /catalog/?q=ps4+games to /video-games/playstation/?q=ps4+games
Redirected from /catalog/?q=shoe+rack to /home-office/?q=shoe+rack
Redirected from /catalog/?q=adidas to /category-fashion-by-jumia/adidas/
Redirected from /catalog/?q=water+heater to /home-office/?q=water+heater
Redirected from /catalog/?q=zte to /phones-tablets/zte/
Redirected from /catalog/?q=clothes to /womens-clothing/
Redirected from /catalog/?q=toaster to /home-office/?q=toaster
Redirected from /catalog/?q=white+sneakers to /category-fashion-by-jumia/?q=white+sneakers
Redirected from /catalog/?q=spark+plus to /phones-tablets/?q=spark+plus
Redirected from /catalog/?q=dildo to /health-beauty/?q=dildo`

var codeRegEx = /\r\n|\n\r|\n|\r/g
pathArray = path.split(codeRegEx)
// var fromTable = document.getElementById('from');
var toTable = document.getElementById('to')
pathArray.forEach(element => {
  var splitElement = element.split(' ')
  // var fromRow = document.createElement('div');
  var toRow = document.createElement('div');

  // fromRow.textContent = splitElement[2];
  toRow.textContent = splitElement[4];
  // fromTable.appendChild(fromRow)
  toTable.appendChild(toRow);
});
